### ISSUE TITLE
Sertifika Kontrolünün ByPass Edilmesi

### ISSUE THREAD

**Issue by boraozturk** [cempehlivan/CP.VPOS#1]
Merhaba, 

Ssl sertifikasının bypass edilmesi normalde tercih edilecek bir durum değil. Güvenlik zaafiyeti yaratabilir.

Koşullu yapayım dedim ama ServicePointManager static bir class. Yük altında race condition yaratabilir. Bir işlemin bypass arzusu alakasız başka bir işlemde de bypassa yol açabilir. 

`ServicePointManager.ServerCertificateValidationCallback = delegate { return true; };`

satırları kaldırılabilir. En iyisi tercihin uygulama tarafına bırakılması bence.

**Comment by cempehlivan** [comment]
Merhaba,
Öneriniz için teşekkürler. Hangi banka olduğu hatırlamıyorum ancak bir banka entegrasyonunda SSL uyarısı veriyordu. Kontrol edeceğim.

**Comment by Jadim11** [comment]
ServicePointManager.ServerCertificateValidationCallback = delegate { return true; };
