### ISSUE TITLE
Isyeri kullanim tipi desteklenmiyor.

### ISSUE THREAD

**Issue by desperado64** [cempehlivan/CP.VPOS#10]
Merhabalar Cem bey,

Projeniz güzel olmuş ellerineize sağlık. Halkbank sanalposunda bana aşağıdaki gibi bir hata dönüyor. Gerçek ortamın responsu alıyorum ama test ortamında da aynı hatayı alıyorum sebebi nedir. 

{
  "result": {
    "statu": 0,
    "message": "Isyeri kullanim tipi desteklenmiyor.",
    "orderNumber": "ACT959",
    "transactionId": null,
    "privateResponse": {
      "oid": "ACT959",
      "Response": "Error",
      "hashAlgorithm": "ver3",
      "encoding": "UTF-8",
      "Ecom_Payment_Card_ExpDate_Month": "12",
      "ProcReturnCode": "99",
      "currency": "949",
      "callbackCall": "true",
      "amount": "1.00",
      "maskedCreditCard": "5342 61** ** ***",
      "islemtipi": "Auth",
      "merchantName": "M*******",
      "Ecom_Payment_Card_ExpDate_Year": "25",
      "storetype": "3d_pay",
      "mdStatus": "7",
      "ErrCode": "3D-1007",
      "failUrl": "********************/Pay/HalkBankCheckOutSales?OrderNumber=ACT959&status=success",
      "clientIp": "....238",
      "installment": "",
      "ErrMsg": "Isyeri kullanim tipi desteklenmiyor.",
      "clientid": "*********",
      "mdErrorMsg": "Isyeri kullanim tipi desteklenmiyor.",
      "MaskedPan": "534261*********",
      "taksit": "",
      "okUrl": "*******************/HalkBankCheckOutSales?OrderNumber=ACT959&status=success",
      "lang": "tr",
      "xid": "eszgP6RyZZtrEVHpBRr9Z7AMfkQ=",
      "HASH": "********************************",
      "rnd": "oSTke8b+uYq2VBTwTOkF"
    }
  },
  "status": true,
  "message": "Başarılı"
}

**Comment by cempehlivan** [comment]
Merhabalar, 3D store type muhtemene "3D" olarak ayarlı. Sanal pos panelinden 3D Store typeınızı kontrol edebilirsiniz. Bunu "3D_PAY" olarak güncelletmeniz gerek. Panelden siz yapamıyorsunuz ancak bir mail ile güncelliyorlar.
