### ISSUE TITLE
bin number listesi 

### ISSUE THREAD

**Issue by suatsuphi** [cempehlivan/CP.VPOS#11]
Merhaba Hocam,

bin number listesini database olarak kullanmak istiyordum BinService internal olarak ayarlanmış bunu public yapmamızda bir sakınca var mı? Manuel olarak da olsa listeyi içeri tek tek deneyerek ekleyebiliyorum. 

bulduğum listede 900 kayıt var bunların 11 tanesi 6 haneli olmayan kayıtlar bunları düzeltmek gerekir mi? 

 <html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/FB/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/FB/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

BIN Numarası | Banka Kodu | Banka Adı | Kart Markası | Kart Tipi | Kart Programı | Ticari Kart
-- | -- | -- | -- | -- | -- | --
97925251 | 135 | Anadolubank | Troy | Credit | Unknown | FALSE
9001203 | 12 | Halkbank | Amex | Credit | Paraf | FALSE
40227801 | 111 | QNB Finansbank | Visa | Credit | CardFinans | FALSE
41556501 | 111 | QNB Finansbank | Visa | Credit | CardFinans | FALSE
52102280 | 111 | QNB Finansbank | MasterCard | Credit | CardFinans | FALSE
97920301 | 111 | QNB Finansbank | Troy | Credit | CardFinans | FALSE
11303200 | 32 | Türk Ekonomi Bankası | Amex | Credit | Unknown | FALSE
51023900 | 32 | Türk Ekonomi Bankası | MasterCard | Credit | Bonus | FALSE
11301500 | 15 | Vakıfbank | Amex | Credit | Unknown | FALSE
9021001 | 15 | Vakıfbank | Visa | Credit | Unknown | FALSE
97926500 | 15 | Vakıfbank | Troy | Credit | Unknown | FALSE

</body>

</html>

 
herhangi bir banka ile çalışmadım projeyi öğrenme amaçlı yapıyorum - bilgi sahibi değilim. Bin Number ları sanal pos ile anlaşma yaptığımız bankadan mı alıyoruz ? hangi sıklıkla güncelleniyor ? banka diğer bankaların da bin numaralarını verebiliyor mu? güncelleme olduğu zaman (tüm bankalar için) bunu talep edebiliyor muyuz ? 

bir de açık topic te oluşan bir durumdan bahsetmiştim... 

proje için tekrar teşekkürler

**Comment by cempehlivan** [comment]
Merhaba, yeni versiyonda bin listesini alabileceğiniz method ekledim.

**Comment by suatsuphi** [comment]
teşekkürler hocam.
