### ISSUE TITLE
Garanti Bankası 3D Problem

### ISSUE THREAD

**Issue by hzrbasaran** [cempehlivan/CP.VPOS#12]
Garanti Bankası 3D işlemlerinde hem Production hemde Test ortamında sistem hatası oluşuyor.

mdStatus => 7
mdErrorMessage => 0122

Hata kodlarına bakılırsa "Sistem Hatası" olarak gözüküyor, fakat Production ortamında da aynı durum oluşuyor.

**Comment by cempehlivan** [comment]
Merhaba, biz de canlıda kullanıyoruz ve garanti bankası sanal posu üzerinden birkaç dakika önce başarılı işlem yapılmış. Daha önce başarılı işlem yapabilmişmiydiniz yoksa yeni mi entegre oluyorsunuz?

**Comment by hzrbasaran** [comment]
Test ortamında verilen test bilgileri ile işlem yapınca sorun çıkarıyor, anladığım kadarıyla yakın zamanda 512 SHA ile kullanım şekli oluşturulmuş. 

Test ortamı için tekrar deneyip bilgile veririm.

**Comment by hzrbasaran** [comment]
Test ortamı bilgileri aşağıdaki gibi

`VirtualPOSAuth posPayment = new()
{
    bankCode = CP.VPOS.Services.BankService.GarantiBBVA,
    merchantID = "7000679",
    merchantUser = "30691298",
    merchantPassword = "123qweASD/",
    merchantStorekey = "12345678",
    testPlatform = true
};`


POST URL :  https://sanalposprovtest.garanti.com.tr/servlet/gt3dengine
`
[mode, TEST]
[apiversion, v0.01]
[version, v0.01]
[secure3dsecuritylevel, 3D_PAY]
[terminalprovuserid, PROVAUT]
[terminaluserid, PROVAUT]
[terminalmerchantid, 7000679]
[terminalid, 30691298]
[txntype, sales]
[txnamount, 10050]
[txncurrencycode, 949]
[txninstallmentcount, ]
[customeripaddress, 1.1.1.1]
[customeremailaddress, test@test.com]
[orderid, 6578ABF1]
[cardnumber, 4355084355084358]
[cardexpiredatemonth, 12]
[cardexpiredateyear, 30]
[cardcvv2, 000]
[successurl, https://localhost:5300/odeme-sonuc]
[errorurl, https://localhost:5300/odeme-sonuc]
[secure3dhash, AC41643D3195C3240280FB97C84B6C018E1D64BA]
`

Response
`[mdstatus, 7]
[mderrormessage, 0122]
[errmsg, 0122]
[clientid, 30691298]
[oid, 6578ABF1]
[response, Error]
[successurl, https://localhost:5300/odeme-sonuc]
[txninstallmentcount, ]
[version, v0.01]
[orderid, 6578ABF1]
[txntype, sales]
[terminalmerchantid, 7000679]
[txnamount, 10050]
[terminaluserid, PROVAUT]
[mode, TEST]
[txncurrencycode, 949]
[secure3dhash, AC41643D3195C3240280FB97C84B6C018E1D64BA]
[apiversion, v0.01]
[errorurl, https://localhost:5300/odeme-sonuc]
[secure3dsecuritylevel, 3D_PAY]
[customeremailaddress, test@test.com]
[customeripaddress, 1.1.1.1]
[terminalprovuserid, PROVAUT]
[terminalid, 30691298]
`

**Comment by hzrbasaran** [comment]
Garanti BBVA açıklaması 
https://dev.garantibbva.com.tr/sanalpos-satis-pesin-3dli

![image](https://github.com/cempehlivan/CP.VPOS/assets/2195077/b33e162f-c69d-4cf3-9107-d9452f08c736)

**Comment by cempehlivan** [comment]
Kullanılan apinin versiyonuna göre hash algoritması değişiyor. Sizin gönderdiğiniz hesaplama mantığı api versiyon 512 için geçerli. Örnekte de görüleceği gibi;
![image](https://github.com/cempehlivan/CP.VPOS/assets/25860078/cb0d7cbd-2e70-4a34-98c2-195604c7bb33)

Bizim projede kullandığımız api versiyonu ise 512 değil. Bu nedenle SHA512 kullanılmıyor. Zaten hash hesabında hata olduğunda "Güvenlik kodu hatalı" şeklinde cevap dönüyor. Test ortamında dönen cevap "0122 - İşleminizi gerçekleştiremiyoruz.Tekrar deneyiniz" dönüyor.

Test ettiğim kadarıyla test ortamı şuan işlem alamıyor evet, ancak yukarıda da bahsettiğim gibi, şuanki kodu canlıda kullanıyoruz ve bir problem bulunmamakta.

**Comment by hzrbasaran** [comment]
Evet canlıda herhangi bir sorun yok ve 512 kullanma zorunluluğuda yok. 
Test ortamı hala bozuk.

İşin komik tarafı Garanti eTicaret destek tarafı bunu kabul etmiyor. 

Canlı ortamda test yaparak entegrasyon yapıldı,

Teşekkürler
