### ISSUE TITLE
Kuveyt Türk ve Albaraka

### ISSUE THREAD

**Issue by viwodev** [cempehlivan/CP.VPOS#15]
Merhaba, sizin kodlarınızı kullanarak Kuveyt Türk ve Albaraka entegrasyonlarını da yaptım.

Ayrıca Nestpay tarafında **3d_pay** modeline alternatif olarak **3d** ödeme modeli için de geliştirme yaptım.
       
mevcut kodlarınıza yaptığım güncellemeleri eklemek isterseniz kodları iletebilirim veya burada paylaşabilirim.

Selamlar

**Comment by cempehlivan** [comment]
Selamlar,
Elinize sağlık. Paylaşırsanız repoya ekleyebilirim.
