### ISSUE TITLE
Url farkları

### ISSUE THREAD

**Issue by ArchitectMag** [cempehlivan/CP.VPOS#17]
Merhabalar incelediğimde test urlleri vs bankaların vermiş olduğu prod veya test urlleri dışında farklı url adreslerine gitmekte. Mesela https://entegrasyon.asseco-see.com.tr/fim/api diye bir apiye gitmekte bu tam olarak güvenlik anlamında ne kadar güvenilir ?

**Comment by cempehlivan** [comment]
Merhabalar, bazı bankalar sanal pos tarafında altyapı olarak asseco nestpay kullanıyor. Hepsinin altyapı sağlayıcısı kendisi olduğu için, test ortamı olarak da kendi url ini veriyorlar. Yani güvenlik açısından hiçbir problem yok. Bankanın kendisi test ortamı olarak zaten burayı kullanın diyor. Bankadan sanal pos dökümanlarını istediğinizde görebilirsiniz.

Prod urller ise yine bankaların verdiği urller. Hangi bankanın prod urlini olması gerektiğinden farklı gördünüz ise iletirseniz kontrol edeyim. Ek olarak, bazen bankalar url değişimine gidebiliyor. Fakat eski urlleri de hemen kapatmıyorlar. Belki 2 yıl yine açık kalıyor. Yeni sanal pos müşterilerini yeni url e yönlendiriyor. Ancak eski url de çalışıyor. garanti.com.tr nin garantibbva.com.tr olması gibi. Bu tarz durumlarda da repoda gerekli güncellemeleri yapıyorum. Çünkü halihazırda bu repoyu aktif olarak kullanıyorum.
