### ISSUE TITLE
Nestpay poslarında storetype parametresi sabit değil sanırım

### ISSUE THREAD

**Issue by kadri1914** [cempehlivan/CP.VPOS#2]
Merhabalar, Halkbank sanal pos entegrasyonu yaparken farkettim ki:

NetspayAbstract.cs içersinde Sale3D fonksiyonunda **storetype** statik olarak **3d_pay** olarak belirlemişsiniz. Ama farkettim ki banka tarafından bize **3d** olarak tanımlama yapılmış.  Bu yüzdendir ki payment3D modeli içerisine storetype diye bir parametre eklense güzel olur düşüncesindeyim.

**Comment by cempehlivan** [comment]
Merhabalar,
Banka tarafındaki storetype "3d" ve "3d_pay" metodlarının çalışma mantığı farklı. "3d" yapılırsa, bankaya 3d için yönlendirme yapıldığında sadece kart sahibi bilgilerini doğrular ve bu kart sahibini onayladım diye response döner. "3d_pay" ise kart sahibi bilgilerini doğruladıysa o an ödemeyi de alır ve response döner. Yani storetype ı parametrik yaparsak storetype seçeneğine göre kodda farklı geliştirme de yapılması gerekmekte.

Bankadan storetype ı "3d_pay" olarak güncellemesini isteyebilirsiniz. Basit bir işlem ve yapıyorlar.
