### ISSUE TITLE
Yapı Kredi yeni TROY kartları geldi, bin noları 8 haneli

### ISSUE THREAD

**Issue by muratsaygili** [cempehlivan/CP.VPOS#4]
Selam, yapı krediden yeni kartlar hakkında e-mail geldi, BinService.cs içindeki datanın devamına ben ekledim buraya da alt kısma eklediğim numaraları yazıyorum, ayrıca ilerleyen dönemlerde ISO tarafından 6 haneli bin uzunluğunun 8 e çıkarılması kararı alınmış gelen mailde bu şekilde yazıyor. Ben kodlara yine 6 hane olarak ekleme yaptım.
https://www.yapikredipos.com.tr/odeme-cozumlerimiz/duyurular/bin-numaralari

{
    ""binNumber"": ""736659"",
    ""bankCode"": ""0067"",
    ""cardType"": 0,
    ""cardBrand"": 2,
    ""commercialCard"": false,
    ""cardProgram"": -1
  },
  {
    ""binNumber"": ""736660"",
    ""bankCode"": ""0067"",
    ""cardType"": 0,
    ""cardBrand"": 2,
    ""commercialCard"": false,
    ""cardProgram"": -1
  },
  {
    ""binNumber"": ""736656"",
    ""bankCode"": ""0067"",
    ""cardType"": 0,
    ""cardBrand"": 2,
    ""commercialCard"": false,
    ""cardProgram"": -1
  },
  {
    ""binNumber"": ""736657"",
    ""bankCode"": ""0067"",
    ""cardType"": 0,
    ""cardBrand"": 2,
    ""commercialCard"": false,
    ""cardProgram"": -1
  },
  {
    ""binNumber"": ""736655"",
    ""bankCode"": ""0067"",
    ""cardType"": 0,
    ""cardBrand"": 2,
    ""commercialCard"": false,
    ""cardProgram"": -1
  },
  {
    ""binNumber"": ""016101"",
    ""bankCode"": ""0067"",
    ""cardType"": 0,
    ""cardBrand"": 2,
    ""commercialCard"": false,
    ""cardProgram"": -1
  },
  {
    ""binNumber"": ""016102"",
    ""bankCode"": ""0067"",
    ""cardType"": 0,
    ""cardBrand"": 2,
    ""commercialCard"": false,
    ""cardProgram"": -1
  },
  {
    ""binNumber"": ""016170"",
    ""bankCode"": ""0067"",
    ""cardType"": 0,
    ""cardBrand"": 2,
    ""commercialCard"": false,
    ""cardProgram"": -1
  },
  {
    ""binNumber"": ""083701"",
    ""bankCode"": ""0067"",
    ""cardType"": 1,
    ""cardBrand"": 2,
    ""commercialCard"": true,
    ""cardProgram"": -1
  },
  {
    ""binNumber"": ""083700"",
    ""bankCode"": ""0067"",
    ""cardType"": 1,
    ""cardBrand"": 2,
    ""commercialCard"": true,
    ""cardProgram"": -1
  },
  {
    ""binNumber"": ""083703"",
    ""bankCode"": ""0067"",
    ""cardType"": 1,
    ""cardBrand"": 2,
    ""commercialCard"": true,
    ""cardProgram"": -1
  }

**Comment by cempehlivan** [comment]
Selamlar, 1.6.0 versiyonunda ekledim. Katkınız için teşekkürler.
