### ISSUE TITLE
taksitlendirme seçenekleri hk

### ISSUE THREAD

**Issue by suatsuphi** [cempehlivan/CP.VPOS#5]
Merhaba,

test bölümünde taksitlendirme ile ilgili örnekler konulabilir mi?

**Comment by cempehlivan** [comment]
Merhabalar,
Ortak poslarda taksit seçenekleri API üzerinden veriliyor. `VPOSClient.BINInstallmentQuery` methodunu kullanarak kartın ilk 6 hanesi ve çekilecek olan tutarı göndererek bu karta yapılabilecek taksit seçeneklerini(varsa) alabilirsiniz.

Ancak direkt olarak bankalardan sanal pos aldıysanız, bankalar bu şekilde servis vermiyor. Bankalar sadece kendine ait kredi kartlarına ve ortaklık programındaki başka banka kartlara taksit yapabiliyor. Mesela garanti bankasından sanal pos aldınız, garanti bankası kredi kartlarına + bonus özellikli başka banka kartlarına taksit yapabiliyor. Yani hem garanti bonus kredi kartına hem de teb bonus kredi kartına taksit yapabilirsiniz. 

Tabi bunun kurgusu tamamiyle manuel ilerliyor. Bankalar kartlarının BIN listesisini API üzerinden vermiyor. Bazılar excel olarak satıcı panelinde paylaşıyor bazılar sanal pos dökümanları sayfasında paylaşıyor. Ben de tüm bankaların BIN bilgilerini toplayıp yine CP.VPOS dll içerisine servis olarak koydum. `VPOSClient.CreditCardBinQuery` methodunu kullanarak BIN numarasına ait detaylı bilgilere ulaşabilirsiniz.  Aynı zamanda bu BIN numarasına hangi bankaların taksit yapabileceği bilgisini de alabilirsiniz. 

Örneğin yapıkredi world özellikli kredi kartını sorguladığınızda `banksWithInstallments` alanında size `["0067", "0015", "0203", "0135"]` şeklinde bu karta taksit yapabilecek banka kodları dönecek. Bu bankalardan herhangi birinde sanal posunuz varsa kendi sisteminizde ilgili banka için tanımladığınız taksit seçeneklerini ekrana yükleyebilirsiniz. Banka entegrasyonun ortak pos mu, taksitler API den mi sorgulanmalı yoksa kendimden mi çekmeliyim? cevaplarını ise `VPOSClient.AllBankList` methodundan sizin bankanızın modelinde `CollectiveVPOS` `true` ise bu ortak postur. `InstallmentAPI` `true` ise taksit seçeneklerini API üzerinden sorgulayabilirsiniz.

Özetle;
Bankadan direkt pos aldıysanız, taksit seçeneklerini kendi sisteminizde tanımlamanız gerekmekte. Girilen kart bilgisine taksit yapabilir miyim kısmında `VPOSClient.CreditCardBinQuery` sorgulamasında bu karta taksit yapabilen bankalar listesinde sizin bankanız varsa taksit yapabilirsiniz.

Bununla ilgili örnekleri unittest e ekleyeceğim.

**Comment by suatsuphi** [comment]
çok teşekkürler taksitlendirme seçeneklerinin mantığını anlamak çok zor bir şeydi tüm detayları vermişsiniz. Test kısmında kendi sisteminizde tanımlamanız mı gerekli kısmını da açıklama anlamında seed data ile örnek koysanız çok mu şey istemiş oluruz? Burada manuel olarak banka nasıl bir taksitlendirme opsiyonları sunuyor ve yine bin numarası üzerinden banka-banka ilerlememiz gerekiyor sanırım örnek bir senaryo tüm olayı çözmemi sağlayabilir... 

teşükkürler bilgilendirme için...

**Comment by suatsuphi** [comment]
Merhaba,
hocam ortak pos sistemi kullanmıyorsak database de bir tabloda hangi bankaya hangi taksitleri uyguladığımızı kaydediyoruz (varsa komisyonu yansıtarak). Bu durumda hangi bankalara desteklediği bilgisine gerek kalmıyor. Biz zaten onları kendi database imize kaydediyoruz. 

**InstallmentOptions**
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/FB/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/FB/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



ID | BankCode | Installment | CommissionPercentage
-- | -- | -- | --
9 | 0046 | 2 | 0
10 | 0047 | 3 | 0
11 | 0048 | 4 | 0
13 | 0049 | 5 | 0



</body>

</html>

foreach (var item in resp.banksWithInstallments)
{
    Console.WriteLine($"bank code: {item}");
}

**Comment by cempehlivan** [comment]
Evet aynen öyle. `CreditCardBinQuery` metodundan kartın bankasını ve hangi banka poslarının bu karta taksit yapabileceğini responsedaki `banksWithInstallments` listinden alıyorsunuz. Bu listedeki bankalar bu karta taksit yapabiliyor. Listedeki bankalardan bir tanesinin sanal posuna sahipseniz onun taksit seçeneklerini db den çekip gösteriyorsunuz ve ödeme işlemini de o banka sanal posunuza gönderiyorsunuz. 
Benim taksit tablom aşağıdaki gibi;

```sql
CREATE TABLE [b2c].[VPOSBankInstallment](
	[BankCode] [VARCHAR](4) NOT NULL,
	[Installment] [TINYINT] NOT NULL,
	[CommissionRate] [REAL] NOT NULL,
 CONSTRAINT [PK_VPOSBankInstallment] PRIMARY KEY CLUSTERED 
(
	[BankCode] ASC,
	[Installment] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 95, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [b2c].[VPOSBankInstallment] ADD  CONSTRAINT [DF_VPOSBankInstallment_CommissionRate]  DEFAULT ((0)) FOR [CommissionRate]
GO

```

**Comment by suatsuphi** [comment]
Teşekkürler hocam... 

ortak pos sistemi ile ilgili bir örneğe ihtiyacım var... ! onun testi var mı? test için kart bilgisine ve api ile taksitlerin nasıl geldiğine

**Comment by cempehlivan** [comment]
iyzico test ortamına kayıt olup api keylerini hemen alabilirsiniz. daha sonra repomuzdaki readme de belirtildiği şekilde iyzico ayarlarınızı girin ve ortak posta nasıl olduğunu test edin.

[https://sandbox-merchant.iyzipay.com/auth/register](https://sandbox-merchant.iyzipay.com/auth/register) buradan kayıt olun.

test kartları ise dökümanlarında mevcut: [https://dev.iyzipay.com/tr/test-kartlari](https://dev.iyzipay.com/tr/test-kartlari)

**Comment by suatsuphi** [comment]
Teşekkürler hocam 
buraya üye oluşturup deneme yapacağım. Kendi banka postumuzu kullandığımızda kart tipini kontrol etmemiz gerekiyor mu?Debit, Credit... Eğer debit karta tek çekim göndermemiz gerekli diye düşünüyorum. Teorik kısmı bilmediğim için detay soruyorum. Debit karta taksit seçeneği gönderirsek sistem hata verir değil mi? (bu karta taksit yapamazsınız şeklinde)
 

if (response.cardType == CP.VPOS.Enums.CreditCardType.Credit)
{
    //taksit seçenekleri
}

**Comment by suatsuphi** [comment]
CreditCardBinQueryResponse modelinin içerisine  bankName `public string bankCode { get; set; }`
 de konulsa VPOSClient.CreditCardBinQuery(bin) sorgularında banka isminin de getirilmesi sağlanabilir mi ?

**Comment by suatsuphi** [comment]
>> sandbox üzerinden deneme yapıyorum ancak "3D Secure doğrulaması geçersiz" hatası alıyorum. bu hatayı nasıl geçebilirim
https://ibb.co/dQM7p8c
https://ibb.co/4pS0KHF

hocam iyzico da hesap oluşturdum. 3d ile ilgili sorun yaşıyorum. Yukarıdaki soruyu iyzico ya ilettim verdikleri cevap aşağıdaki gibidir. Akbak test işleminde sorun çıkmıyor 3d yi geçebiliyorum ancak iyzico da hata alıyorum. Yukarıdaki resimdeki gibi kodu giriyorum 3D Secure doğrulaması geçersiz diyor. 

<details><summary>Details</summary>
<p>

Merhaba,
 
İletmiş olduğunuz bilgiler için teşekkür ederiz. Sms onay aşaması (OTP) başarılı gerçekleştiğini görüntülemekteyiz. mdStatus = 1 --> Doğrulama başarılıdır. 3ds ilk aşaması başarılı tamamalanmıştır. Request belirtmiş olduğunuz callbackUrl adresinize 3ds şifresi girdikten sonra callbackUrl adresinize paymentID, conversationID ve conversationData parametreleri post edilir. Bu parametreler ile bir sorgu daha gerçekleştirip ödemeyi tamamlayabilirsiniz.

https://github.com/iyzico/iyzipay-php/blob/master/samples/create_threeds_payment.php

Ek olarak kontrolünüzü rica ederiz;
Entegrasyon sırasında sandbox(test) ortamının api anahtarları ile product(gerçek ortam) endpointi kullanıldığında bu hata mesajı alınabilmektedir. 

https://merchant.iyzipay.com/login panelinizin ayarlar - firma ayarları sekmesinde bulunan api ve güvenlik anahtarlarını kullanıyorsanız baseurl değeri olarak https://api.iyzipay.com

https://sandbox-merchant.iyzipay.com/login panelinizin ayarlar - firma ayarları sekmesinde bulunan api ve güvenlik anahtarlarını kullanıyorsanız baseurl değeri olarak https://sandbox-api.iyzipay.com baseurl değerini kullanmalısınız.

Saygılarımla,

</p>
</details>
