### ISSUE TITLE
Payten / Asseco Nestpay Hash v3

### ISSUE THREAD

**Issue by ginasoftas** [cempehlivan/CP.VPOS#6]
Merhaba,
Elinize sağlık öncelikle. 31 Temmuz 2023den itibaren Hash V3 kullanılması gerekiyor sanırım. Bununla alakalı geliştirme yapılacak mısınız?

**Comment by cempehlivan** [comment]
Merhabalar,
Rica ederim, projeyi beğenmenize sevindim.
Sorunuz üzerine asseco ile iletişime geçtim. Bana verdikleri yanıt şu şekilde: 

_"Mevcut durumda Hash 1 versiyonumuzu kullanan işyerlerimize, en kısa zamanda Hash 3 versiyonumuza geçmelerini önermekteyiz. Fraud atakları ve riskleri minimize etmek amacıyla Hash 3 versiyonumuzun kullanımı önemlidir. Hash 3 versiyon, 1 versiyona göre daha az fraud riski içermektedir, versiyon 3'e geçmeyen işyerleri bu riski kabul etmiş sayılacaktır. Ekte Hash versiyon 3 dokümanları iletilmiştir."_

Yani hash 3 olmasada kullanım devam edecek ancak bazı yükümlülükleri kabul etmeyeceklerini anlıyorum.

Ancak yinede 31 Temmuz'a kadar güncelleme yapacağım.


[Hash3-versiyon-dokumani.pdf](https://github.com/cempehlivan/CP.VPOS/files/12095195/Hash3-versiyon-dokumani.pdf)
[Hashv3_Sample_Codes.zip](https://github.com/cempehlivan/CP.VPOS/files/12095196/Hashv3_Sample_Codes.zip)

**Comment by cempehlivan** [comment]
1.6.1 versiyonunda hash v3 e geçildi. Teşekkürler.

**Comment by mrthanbrr** [comment]
ASP.NET C# Uygulamasını geliştiren varsa, Hash Version 3 Güncellemesi ile alakalı yardım almak isteyen olursa. 
Yardımcı olabilirim. Mail Adresim: mrtbrr@gmail.com yada burdanda yazabilirsiniz.
