### ISSUE TITLE
3d ödeme ile ilgili hata mesajı?

### ISSUE THREAD

**Issue by suatsuphi** [cempehlivan/CP.VPOS#7]
Merhaba,

Aşağıdaki 3d ile ödemede aşağıdaki gibi hata alıyorum. 3d yi kapattığım zaman sorunsuz kayıt oluyor.
https://ibb.co/LPjtcD2 

response.statu = Error
response.message = "İşlem sırasında bilinmeyen bir hata oluştu"

```
        public IActionResult VirtualPOS3DResponse()
        {
            var request = _httpContextAccessor.HttpContext?.Request;
            Dictionary<string, object> pairs = request.Form.Keys.ToDictionary(k => k, v => (object)request.Form[v]);
            SaleResponse response = VPOSClient.Sale3DResponse(new Sale3DResponseRequest
            {
                responseArray = pairs
            }, GetBankInfo().Result);

            if (response.statu == CP.VPOS.Enums.SaleResponseStatu.Success)
            {
                var messages = new List<string>();
                var state = new OnlinePaymentCheckoutState();
                var redirectUrl = Url.Action(nameof(CheckoutController.Confirm), "Checkout", new { area = string.Empty }, request.Scheme).TrimEnd('/');
                state.IsConfirmed = true;
                state.SubmitForm = true;
                state.FormData = redirectUrl;
                _httpContextAccessor.HttpContext.Session.TrySetObject("OnlinePaymentCheckoutState", state);
                return RedirectToAction(nameof(CheckoutController.Confirm), "Checkout");
            }
            else
            {
                Logger.Error(response.message);
                NotifyError(response.message);
                return RedirectToAction(nameof(CheckoutController.PaymentMethod), "Checkout");
            }
        }
```

sID | 1
-- | --
oid | 23a937d4-063d-4e42-9e95-8634ed2abdc9
hashAlgorithm | ver3
encoding | ISO-8859-9
Ecom_Payment_Card_ExpDate_Month | 12
version | 2
currency | 949
dsId | 1
callbackCall | TRUE
amount | 18.69
maskedCreditCard | 4355 08** **** 4358
islemtipi | Auth
merchantName | Akbank
ACQBIN | 490740
PAResSyntaxOK | TRUE
Ecom_Payment_Card_ExpDate_Year | 30
storetype | 3d_pay
mdStatus | 0
failUrl | https://localhost:44325/onlinepayment/virtualpos3dresponse
clientIp | 5.21.104.95
installment |  
merchantID | 100100000
mdErrorMsg | Not authenticated
clientid | 100100000
MaskedPan | 435508***4358
txstatus | N
digest | digest
PAResVerified | TRUE
taksit |  
okUrl | https://localhost:44325/onlinepayment/virtualpos3dresponse
md | 435508:E22686B70BB6B3C699EF5CBEE1463224280DF284EC5C336DA015D0257492D543:4089:##100100000
lang | tr
xid | mw4fVcBqfYqFKbxqdZe4e7zMPOo=
TRANID |  
HASH | vFSr8JaXyp0+/1i4IPZbdS/l92HdcN3ocmWhWgnfmbd5we2ddvGW9j0OS1WbnbvYmFbTTIcdQYEEF7Q4lS7vDg==
rnd | 9KtgsP9cSyDptzMPvQtj

**Comment by cempehlivan** [comment]
Merhabalar,

Test ortamında test ediyorsunuz sanırım. 4355 08** **** 4358 test kartı kullanıma kapatılmış. Aşağıdaki test kartı bilgileriyle test edebilir misiniz?

4508034508034509
12 / 2026
000

**Comment by suatsuphi** [comment]
teşekkürler hocam.... dediğiniz gibi karttan kaynaklı bir sorunmuş. şu an çalışıyor. 
taksitlendirme konusu kaldı sadece kendi unittest ekleyeceğiniz örneği bekliyorum. taksit mantığını da öğrenmiş olmayı umuyorum. Bankadan direkt pos aldıysak banka bize şu karta bu kadar taksit yapabilirsiniz diyor sanırım (anlattığınızdan anladığım). bununla ilgili bir örnek seed data ile yapılabilir mi? Ortak pos ve api olayının mantığını anlamadım. Ortak post ne demek ortak post apiden gelmiyorsa yine sistemden mi bilgiye bakacağız ?

**Comment by suatsuphi** [comment]
şimdi de geçersiz url sayfası dönüyor.

**Comment by suatsuphi** [comment]
şimdi de Geçersiz Url hatası vermeye başladı... 
bununla ilgi destek veren hangi kurum destek alabileceğimiz bir yer var mı? url de asseco diye bir adres geçiyor destek verir mi ? fazla deneme yaptığım için ip yada kartı bloke etmiş olabilirler mi? başka bir kredi kartı nasıl bulabilirim ?

**Comment by cempehlivan** [comment]
destek.est@asseco-see.com.tr mail adresinden destek alabilirsiniz
